// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Identity.B2b.Presentation.Web.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using System.ComponentModel.DataAnnotations;

    public partial class Invitation
    {
        /// <summary>
        /// Initializes a new instance of the Invitation class.
        /// </summary>
        public Invitation() { }

        /// <summary>
        /// Initializes a new instance of the Invitation class.
        /// </summary>
        public Invitation(string invitedUserDisplayName = default(string), string invitedUserEmailAddress = default(string), bool? sendInvitationMessage = default(bool?), string inviteRedirectUrl = default(string), string inviteUrl = default(string))
        {
            InvitedUserDisplayName = invitedUserDisplayName;
            InvitedUserEmailAddress = invitedUserEmailAddress;
            SendInvitationMessage = sendInvitationMessage;
            InviteRedirectUrl = inviteRedirectUrl;
            InviteUrl = inviteUrl;
        }

        /// <summary>
        /// </summary>
        [Display(Name = "Name")]
        [Required]
        [JsonProperty(PropertyName = "InvitedUserDisplayName")]
        public string InvitedUserDisplayName { get; set; }

        /// <summary>
        /// </summary>
        [Display(Name = "Email Address")]
        [Required]
        [JsonProperty(PropertyName = "InvitedUserEmailAddress")]
        public string InvitedUserEmailAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SendInvitationMessage")]
        public bool? SendInvitationMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InviteRedirectUrl")]
        public string InviteRedirectUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InviteUrl")]
        public string InviteUrl { get; set; }

    }
}
